### ISSUE TITLE
HowTo take care of changes made by ansible `handlers`?

### ISSUE THREAD

**Issue by martin-v** [fxkr/ansible-etckeeper#1]
Hi Felix,

any ideas how to take care of changes made by ansible `handlers`? E.g. following handler causes changes in `/etc/aliases.db`:

```yml
- name: Reload aliases
  command: newaliases
```

Thanks
  martin

**Comment by fxkr** [comment]
Personally I would probably make `newaliases` a task and gate it with `when:` instead of relying on `notify`, based on a personal rule of thumb that things that change persistent state should be tasks, and only things like daemon restarts to pickup the new state should be handlers. This would have the benefit of grouping the execution of related changes (change of /etc/mail/aliases, change of DB) together. This will also improve the order of git commits.

Alternatively you should be able to convert your handler to `listen` (this is probably necessary, to avoid a name conflict, but might not be, I have not tested it. The [documentation](https://docs.ansible.com/ansible/latest/user_guide/playbooks_intro.html#handlers-running-operations-on-change) is ambiguous). Then you can add a handler like the following textually after the `Reload aliases` handler (handlers execute in the order in which they are defined):

```
- name: Update etckeeper for newaliases
  etckeeper: action=commit msg="newaliases"
  listen: "Reload aliases"
```

I have not tested above. I would appreciate if you can confirm if this does or does not solve your problem.

**Comment by martin-v** [comment]
Thx, I will test it and give you an update in a few days.

**Comment by martin-v** [comment]
Worked well, thx.
